name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python3 -m pip install build --user
      - run: python3 -m build --sdist --wheel --outdir dist/ .
      - uses: actions/upload-artifact@v3
        with:
          name: doppler-sdk
          path: dist/ 
  
  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/doppler-sdk
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: doppler-sdk
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
